version: '3.8'

services:
  api-gateway-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    restart: always
    networks:
      - api-gateway

networks:
  api-gateway:
