version: '1.0'

services:

  api-gateway-backend:
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - 8080:8080
    restart: always
    networks:
      - api-gateway

networks:
  api-gateway:    