databases:
  - database: "bioportal"
    url: "https://data.biodivportal.gfbio.dev/search?q=%s&apikey=%s"
    apiKey: "53a72292-cb9e-4855-acac-4676fc9eaa41"
    responseMapping:
      nestedJson: "collection"
      iri: "@id"
      label: "prefLabel"
      source: "links.ontology"  
      synonym: "links.synonym" 
      ontology: "ontologyType"
  - database: "ols"
    url: "https://ebi.ac.uk/ols4/api/search?q=%s"
    apiKey: ""
    responseMapping:
      nestedJson: "response"  
      key: "docs" # hashmap --> key for the array of results
      iri: "iri"
      label: "label"
      source: "ontology_name"
      synonym: "short_form"  
      ontology: "ontology_prefix"
  - database: "gfbio"
    url: "https://terminologies.gfbio.org/api/terminologies/search?query=%s"
    apiKey: ""
    responseMapping:
      nestedJson: "results"
      iri: "uri"
      label: "label"
      source: "sourceTerminology"
      synonym: "description" 
      ontology: "internal"