search:
  ontologies:
    - name: Bioportal
      apiKey: 53a72292-cb9e-4855-acac-4676fc9eaa41
      fields: 
        -iri
        -label
        -source
        -synonym
        -ontology
    - name: OLS
      fields: 
        -iri
        -label
        -source
        -synonym 
        -ontology