dbSchema:
  ols:
    mapping:
      label: "label"
      iri: "iri"
      ontology: "ontology_name"
      synonym: "synonym"
      description: "description"
      shortForm: "short_form"
  ontoportal:
    mapping:
      label: "prefLabel"
      iri: "@id"
      synonym: "synonym"
      ontology: "@type"
      description: "definition"