databases:
  - database: "bioportal"
    url: "https://data.biodivportal.gfbio.dev/search?q=%s&apikey=%s"
    apiKey: "53a72292-cb9e-4855-acac-4676fc9eaa41"
    responseMapping:
      nestedJson: "collection"
      label: "prefLabel"
      iri: "@id"
      synonym: "synonym"
      ontology: "links"
      description: "@context"
  - database: "ols"
    url: "https://ebi.ac.uk/ols4/api/search?q=%s"
    apiKey: ""
    responseMapping:
      nestedJson: "response"
      key: "docs" # hashmap --> key for the array of results
      label: "label"
      iri: "iri"
      ontology: "ontology_name"
      synonym: "short_form"
      description: "description"
  - database: "gfbio"
    url: "https://terminologies.gfbio.org/api/terminologies/search?query=%s"
    apiKey: ""
    responseMapping:
      nestedJson: "results"
      label: "label"
      iri: "uri"
      synonym: "synonym"
      ontology: "sourceTerminology"
      description: "description"


# Add mappings for new databases here: e.g
#  - database: "AGRO"
#      responseMapping:
#        iri: "iri"
#        label: "label"
#        synonym: "synonym"
#        description: "description"
#        source: "source"
#        ontology: "ontology"