databases:
  - database: "ontoportal"
    url: "https://data.biodivportal.gfbio.dev/search?q=%s&apikey=%s"
    apiKey: "47a57aa3-7b54-4f34-b695-dbb5f5b7363e" # replace with your own API key
    responseMapping:
      nestedJson: "collection"
      label: "prefLabel"
      iri: "@id"
      synonym: "synonym"
      ontology: "links"
      description: "definition"
      type: "@type"
  - database: "ols"
    url: "https://ebi.ac.uk/ols4/api/select?q=%s"
    apiKey: ""
    responseMapping:
      nestedJson: "response"
      key: "docs" # hashmap --> key for the array of results
      label: "label"
      iri: "iri"
      ontology: "ontology_name"
      synonym: "synonym"
      shortForm: "short_form"
      description: "description"
      type: "type"
  - database: "gfbio"
    url: "https://terminologies.gfbio.org/api/terminologies/search?query=%s"
    apiKey: ""
    responseMapping:
      nestedJson: "results"
      label: "label"
      iri: "uri"
      synonym: "synonym"
      ontology: "sourceTerminology"
      description: "description"


# Add mappings for new databases here: e.g
#  - database: "AGRO"
#      responseMapping:
#        iri: "iri"
#        label: "label"
#        synonym: "synonym"
#        description: "description"
#        source: "source"
#        ontology: "ontology"
